
import { Drink, ModifierGroup, ModifierOption, Discount, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
    { id: 'cat-1', name: 'Hot Drinks', imageUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=100&q=50' },
    { id: 'cat-2', name: 'Iced Drinks', imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=100&q=50' },
    { id: 'cat-3', name: 'Teas', imageUrl: 'https://images.unsplash.com/photo-1573326140384-031e6ab9b48f?auto=format&fit=crop&w=100&q=50' },
    { id: 'cat-5', name: 'Uncategorised' }, // Fallback category
];

export const INITIAL_MODIFIERS: ModifierGroup[] = [
  {
    id: 'mod-group-1',
    name: 'Milk Type',
    options: [
      { id: 'mod-1-1', name: 'Full Cream', price: 0.0, cost: 0.1 },
      { id: 'mod-1-2', name: 'Light', price: 0.0, cost: 0.1 },
      { id: 'mod-1-3', name: 'Almond', price: 0.75, cost: 0.25 },
      { id: 'mod-1-4', name: 'Soy', price: 0.5, cost: 0.2 },
      { id: 'mod-1-5', name: 'Oat', price: 0.75, cost: 0.25 },
      { id: 'mod-1-6', name: 'Lactose Free', price: 0.75, cost: 0.25 },
    ],
    isRequired: true,
    defaultOptionId: 'mod-1-1',
  },
  {
    id: 'mod-group-2',
    name: 'Sweetness',
    options: [
      { id: 'mod-2-1', name: 'Sugar', price: 0.0, cost: 0.05 },
      { id: 'mod-2-3', name: 'Vanilla Syrup', price: 0.5, cost: 0.15 },
    ],
    isRequired: false,
    allowQuantity: true,
    allowMultiple: true,
  },
  {
    id: 'mod-group-3',
    name: 'Espresso',
    options: [
      { id: 'mod-3-1', name: 'Extra Shot', price: 0.5, cost: 0.4 },
    ],
    isRequired: false,
    allowQuantity: true,
  },
  {
    id: 'mod-group-4',
    name: 'Chocolate',
    options: [
      { id: 'mod-4-1', name: 'Extra Milk Chocolate', price: 0.5, cost: 0.2 },
      { id: 'mod-4-2', name: 'Extra White Chocolate', price: 0.5, cost: 0.2 },
    ],
    isRequired: false,
  },
  {
    id: 'mod-group-5',
    name: 'Marshmallow',
    options: [
      { id: 'mod-5-1', name: 'In', price: 0.0, cost: 0.1 },
      { id: 'mod-5-2', name: 'Out', price: 0.0, cost: 0.0 },
    ],
    isRequired: false,
  },
];

const IMG_PARAMS = '?auto=format&fit=crop&w=300&q=40';

export const INITIAL_DRINKS: Drink[] = [
  // Hot Drinks
  {
    id: 'drink-1',
    name: 'Latte',
    category: 'cat-1',
    basePrice: 4.0,
    baseCost: 1.2,
    imageUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3'],
    description: 'One part espresso, two parts steamed milk, and a thin layer of foam (approx. 1cm). A creamy, milk-forward coffee.',
  },
  {
    id: 'drink-2',
    name: 'Cappuccino',
    category: 'cat-1',
    basePrice: 4.0,
    baseCost: 1.1,
    imageUrl: 'https://images.unsplash.com/photo-1572442388796-11668a65342d' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3'],
    description: 'Equal parts espresso, steamed milk, and thick milk foam (1:1:1 ratio). A classic balanced and frothy delight.',
  },
  {
    id: 'drink-3',
    name: 'Flat White',
    category: 'cat-1',
    basePrice: 4.0,
    baseCost: 1.3,
    imageUrl: 'https://images.unsplash.com/photo-1596707442116-232537a7442a' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3'],
    description: 'One part espresso with two parts thin, velvety microfoam milk. Richer and more coffee-focused than a latte.',
  },
  {
    id: 'drink-4',
    name: 'Short Black',
    category: 'cat-1',
    basePrice: 3.0,
    baseCost: 0.8,
    imageUrl: 'https://images.unsplash.com/photo-1621267860477-1632432a8314' + IMG_PARAMS,
    modifierGroups: ['mod-group-3'],
    description: 'A pure 30ml shot of intense espresso with a rich crema. The foundation of all our coffee drinks.',
  },
  {
    id: 'drink-5',
    name: 'Long Black',
    category: 'cat-1',
    basePrice: 3.5,
    baseCost: 0.9,
    imageUrl: 'https://images.unsplash.com/photo-1518004856236-717c5dbb03f1' + IMG_PARAMS,
    modifierGroups: ['mod-group-3'],
    description: 'Two shots of espresso pulled over hot water (1:2 ratio) to preserve the delicate crema and aroma.',
  },
  {
    id: 'drink-6',
    name: 'Macchiato',
    category: 'cat-1',
    basePrice: 3.25,
    baseCost: 0.9,
    imageUrl: 'https://images.unsplash.com/photo-1561737710-60a5b6fcf01b' + IMG_PARAMS,
    modifierGroups: ['mod-group-3'],
    description: "A shot of espresso 'stained' with a small dollop of steamed milk foam. Bold coffee with a touch of creaminess.",
  },
  {
    id: 'drink-7',
    name: 'Hot Chocolate',
    category: 'cat-1',
    basePrice: 4.5,
    baseCost: 1.3,
    imageUrl: 'https://images.unsplash.com/photo-1605333240291-05a8d9a43fe4' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-4', 'mod-group-5'],
    description: 'Rich cocoa blended with steamed milk and a light layer of foam. A comforting, sweet classic.',
  },
  {
    id: 'drink-8',
    name: 'Mocha',
    category: 'cat-1',
    basePrice: 4.75,
    baseCost: 1.4,
    imageUrl: 'https://images.unsplash.com/photo-1577968897966-3d4325b36def' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3', 'mod-group-4'],
    description: 'A delicious 1:1:1 blend of espresso, chocolate, and steamed milk. The perfect marriage of coffee and cocoa.',
  },
  {
    id: 'drink-22',
    name: 'Americano',
    category: 'cat-1',
    basePrice: 3.50,
    baseCost: 0.8,
    imageUrl: 'https://images.unsplash.com/photo-1593443320739-7356223b3a43' + IMG_PARAMS,
    modifierGroups: ['mod-group-3'],
    description: 'A shot of espresso diluted with hot water for a lighter body similar to drip coffee.',
  },
  // Teas
  {
    id: 'drink-11',
    name: 'Chai Latte',
    category: 'cat-3',
    basePrice: 4.5,
    baseCost: 1.4,
    imageUrl: 'https://images.unsplash.com/photo-1573326140384-031e6ab9b48f' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2'],
    description: 'A fragrant blend of spiced black tea and steamed milk (1:3 ratio). Warm, aromatic, and soothing.',
  },
  {
    id: 'drink-12',
    name: 'Dirty Chai',
    category: 'cat-3',
    basePrice: 5.00,
    baseCost: 1.8,
    imageUrl: 'https://images.unsplash.com/photo-1594744453366-e84084724810' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3'],
    description: 'Our classic spiced chai latte with an added shot of bold espresso for a caffeine kick.',
  },
  {
    id: 'drink-13',
    name: 'Sticky Chai',
    category: 'cat-3',
    basePrice: 5.0,
    baseCost: 1.8,
    imageUrl: 'https://images.unsplash.com/photo-1601923161314-54c7a6591741' + IMG_PARAMS,
    modifierGroups: ['mod-group-1'],
    description: 'Premium loose-leaf tea and spices cured in honey, brewed with creamy steamed milk.',
  },
  {
    id: 'drink-14',
    name: 'Matcha Latte',
    category: 'cat-3',
    basePrice: 4.75,
    baseCost: 1.5,
    imageUrl: 'https://images.unsplash.com/photo-1563514212933-2023a100db27' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2'],
    description: 'High-grade Japanese green tea powder whisked with steamed milk. Earthy, vibrant, and antioxidant-rich.',
  },
  // Iced Drinks
  {
    id: 'drink-15',
    name: 'Iced Coffee',
    category: 'cat-2',
    basePrice: 4.25,
    baseCost: 1.0,
    imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3'],
    description: 'Chilled espresso mixed with cold milk and served over ice. Refreshing and energizing.',
  },
  {
    id: 'drink-19',
    name: 'Iced Latte',
    category: 'cat-2',
    basePrice: 4.25,
    baseCost: 1.2,
    imageUrl: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3'],
    description: 'A bold shot of espresso poured over cold milk and ice. A crisp, clean, and cool coffee experience.',
  },
  {
    id: 'drink-20',
    name: 'Iced Chocolate',
    category: 'cat-2',
    basePrice: 4.75,
    baseCost: 1.5,
    imageUrl: 'https://images.unsplash.com/photo-1587882390399-190644f0525d' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-4'],
    description: 'Decadent chocolate syrup swirled with cold milk and served over plenty of ice.',
  },
  {
    id: 'drink-21',
    name: 'Iced Matcha Latte',
    category: 'cat-2',
    basePrice: 5.00,
    baseCost: 1.6,
    imageUrl: 'https://images.unsplash.com/photo-1509082025158-6c827339734e' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2'],
    description: 'Vibrant matcha green tea whisked with cold milk and served over ice for a refreshing boost.',
  },
];

export const INITIAL_DISCOUNTS: Discount[] = [
    { id: 'disc-1', code: 'STAFF10', type: 'percentage', value: 10 },
    { id: 'disc-2', code: '50OFF', type: 'percentage', value: 50 },
    { id: 'disc-3', code: '2DOLLARSOFF', type: 'fixed', value: 2 },
];

export const COFFEE_JOKES = [
  "What do you call a sad cup of coffee? Depresso.",
  "How did the hipster burn his tongue? He drank his coffee before it was cool.",
  "What’s the best Beatles song? Latte Be!",
  "Why are programmers so bad at making coffee? They can't handle the exceptions.",
  "What's it called when you steal someone's coffee? Mugging!",
  "How does Moses make his coffee? Hebrews it.",
  "What's the opposite of coffee? Sneezy.",
];
