
import { Drink, ModifierGroup, ModifierOption, Discount, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
    { id: 'cat-1', name: 'Hot Drinks', imageUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=100&q=50' },
    { id: 'cat-2', name: 'Iced Drinks', imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=100&q=50' },
    { id: 'cat-3', name: 'Teas', imageUrl: 'https://images.unsplash.com/photo-1573326140384-031e6ab9b48f?auto=format&fit=crop&w=100&q=50' },
    { id: 'cat-4', name: 'Other', imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=100&q=50' },
    { id: 'cat-5', name: 'Uncategorised' }, // Fallback category
];

export const INITIAL_MODIFIERS: ModifierGroup[] = [
  {
    id: 'mod-group-1',
    name: 'Milk Type',
    options: [
      { id: 'mod-1-1', name: 'Full Cream', price: 0.0, cost: 0.1 },
      { id: 'mod-1-2', name: 'Light', price: 0.0, cost: 0.1 },
      { id: 'mod-1-3', name: 'Almond', price: 0.75, cost: 0.25 },
      { id: 'mod-1-4', name: 'Soy', price: 0.5, cost: 0.2 },
      { id: 'mod-1-5', name: 'Oat', price: 0.75, cost: 0.25 },
      { id: 'mod-1-6', name: 'Lactose Free', price: 0.75, cost: 0.25 },
    ],
    isRequired: true,
    defaultOptionId: 'mod-1-1',
  },
  {
    id: 'mod-group-2',
    name: 'Sweetness',
    options: [
      { id: 'mod-2-1', name: 'Sugar', price: 0.0, cost: 0.05 },
      { id: 'mod-2-3', name: 'Vanilla Syrup', price: 0.5, cost: 0.15 },
    ],
    isRequired: false,
    allowQuantity: true,
    allowMultiple: true,
  },
  {
    id: 'mod-group-3',
    name: 'Espresso',
    options: [
      { id: 'mod-3-1', name: 'Extra Shot', price: 0.5, cost: 0.4 },
    ],
    isRequired: false,
    allowQuantity: true,
  },
  {
    id: 'mod-group-4',
    name: 'Chocolate',
    options: [
      { id: 'mod-4-1', name: 'Extra Milk Chocolate', price: 0.5, cost: 0.2 },
      { id: 'mod-4-2', name: 'Extra White Chocolate', price: 0.5, cost: 0.2 },
    ],
    isRequired: false,
  },
  {
    id: 'mod-group-5',
    name: 'Marshmallow',
    options: [
      { id: 'mod-5-1', name: 'In', price: 0.0, cost: 0.1 },
      { id: 'mod-5-2', name: 'Out', price: 0.0, cost: 0.0 },
    ],
    isRequired: false,
  },
];

const IMG_PARAMS = '?auto=format&fit=crop&w=300&q=40';

export const INITIAL_DRINKS: Drink[] = [
  // Hot Drinks
  {
    id: 'drink-1',
    name: 'Latte',
    category: 'cat-1',
    basePrice: 4.0,
    baseCost: 1.2,
    imageUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3'],
    description: 'A smooth, creamy coffee made with a shot of espresso and steamed milk.',
  },
  {
    id: 'drink-2',
    name: 'Cappuccino',
    category: 'cat-1',
    basePrice: 4.0,
    baseCost: 1.1,
    imageUrl: 'https://images.unsplash.com/photo-1572442388796-11668a65342d' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3'],
    description: 'The perfect balance of espresso, steamed milk, and a thick layer of foam.',
  },
  {
    id: 'drink-3',
    name: 'Flat White',
    category: 'cat-1',
    basePrice: 4.0,
    baseCost: 1.3,
    imageUrl: 'https://images.unsplash.com/photo-1596707442116-232537a7442a' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3'],
    description: 'A rich espresso shot topped with velvety steamed milk for a smooth finish.',
  },
  {
    id: 'drink-4',
    name: 'Short Black',
    category: 'cat-1',
    basePrice: 3.0,
    baseCost: 0.8,
    imageUrl: 'https://images.unsplash.com/photo-1621267860477-1632432a8314' + IMG_PARAMS,
    modifierGroups: ['mod-group-3'],
    description: 'A pure, intense shot of espresso, also known as an espresso.',
  },
  {
    id: 'drink-5',
    name: 'Long Black',
    category: 'cat-1',
    basePrice: 3.5,
    baseCost: 0.9,
    imageUrl: 'https://images.unsplash.com/photo-1518004856236-717c5dbb03f1' + IMG_PARAMS,
    modifierGroups: ['mod-group-3'],
    description: 'A double-shot of espresso pulled over hot water to retain its crema.',
  },
  {
    id: 'drink-6',
    name: 'Macchiato',
    category: 'cat-1',
    basePrice: 3.25,
    baseCost: 0.9,
    imageUrl: 'https://images.unsplash.com/photo-1561737710-60a5b6fcf01b' + IMG_PARAMS,
    modifierGroups: ['mod-group-3'],
    description: "A bold shot of espresso 'stained' with a small dollop of steamed milk froth.",
  },
  {
    id: 'drink-7',
    name: 'Hot Chocolate',
    category: 'cat-1',
    basePrice: 4.5,
    baseCost: 1.3,
    imageUrl: 'https://images.unsplash.com/photo-1605333240291-05a8d9a43fe4' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-4', 'mod-group-5'],
    description: 'Rich, decadent chocolate melted into creamy steamed milk.',
  },
  {
    id: 'drink-8',
    name: 'Mocha',
    category: 'cat-1',
    basePrice: 4.75,
    baseCost: 1.4,
    imageUrl: 'https://images.unsplash.com/photo-1577968897966-3d4325b36def' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3', 'mod-group-4'],
    description: 'A delicious blend of rich chocolate, espresso, and steamed milk.',
  },
  {
    id: 'drink-9',
    name: 'White Hot Chocolate',
    category: 'cat-1',
    basePrice: 4.5,
    baseCost: 1.5,
    imageUrl: 'https://images.unsplash.com/photo-1572498284483-7923a105d3b3' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-4', 'mod-group-5'],
    description: 'A creamy and sweet alternative made from rich white chocolate and steamed milk.',
  },
  {
    id: 'drink-10',
    name: 'Piccolo',
    category: 'cat-1',
    basePrice: 3.5,
    baseCost: 1.0,
    imageUrl: 'https://images.unsplash.com/photo-1616870830113-a41ac2a2f814' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-3'],
    description: 'A mini latte with a restricted ristretto shot for a strong, balanced flavour.',
  },
  {
    id: 'drink-22',
    name: 'Americano',
    category: 'cat-1',
    basePrice: 3.50,
    baseCost: 0.8,
    imageUrl: 'https://images.unsplash.com/photo-1593443320739-7356223b3a43' + IMG_PARAMS,
    modifierGroups: ['mod-group-3'],
    description: 'A shot of espresso diluted with hot water, giving it a similar strength to, but different flavor from, traditionally brewed coffee.',
  },
  // Teas
  {
    id: 'drink-11',
    name: 'Chai Latte',
    category: 'cat-3',
    basePrice: 4.5,
    baseCost: 1.4,
    imageUrl: 'https://images.unsplash.com/photo-1573326140384-031e6ab9b48f' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2'],
    description: 'A sweet and spicy blend of black tea, aromatic spices, and steamed milk.',
  },
  {
    id: 'drink-12',
    name: 'Dirty Chai',
    category: 'cat-3',
    basePrice: 5.00,
    baseCost: 1.8,
    imageUrl: 'https://images.unsplash.com/photo-1594744453366-e84084724810' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3'],
    description: 'A classic chai latte with an added shot of espresso for an extra kick.',
  },
  {
    id: 'drink-13',
    name: 'Sticky Chai',
    category: 'cat-3',
    basePrice: 5.0,
    baseCost: 1.8,
    imageUrl: 'https://images.unsplash.com/photo-1601923161314-54c7a6591741' + IMG_PARAMS,
    modifierGroups: ['mod-group-1'],
    description: 'Aromatic chai spices and black tea candied in honey, brewed to perfection.',
  },
  {
    id: 'drink-14',
    name: 'Matcha Latte',
    category: 'cat-3',
    basePrice: 4.75,
    baseCost: 1.5,
    imageUrl: 'https://images.unsplash.com/photo-1563514212933-2023a100db27' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2'],
    description: 'Vibrant Japanese green tea powder whisked with steamed milk.',
  },
  {
    id: 'drink-24',
    name: 'English Breakfast Tea',
    category: 'cat-3',
    basePrice: 3.50,
    baseCost: 0.5,
    imageUrl: 'https://images.unsplash.com/photo-1589136113881-857b32f91a66' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2'],
    description: 'A traditional blend of black teas originating from Assam, Ceylon and Kenya. A robust, full-bodied tea.',
  },
  // Iced Drinks
  {
    id: 'drink-15',
    name: 'Iced Coffee',
    category: 'cat-2',
    basePrice: 4.25,
    baseCost: 1.0,
    imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3'],
    description: 'Chilled coffee served over ice, perfect for a warm day.',
  },
  {
    id: 'drink-19',
    name: 'Iced Latte',
    category: 'cat-2',
    basePrice: 4.25,
    baseCost: 1.2,
    imageUrl: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2', 'mod-group-3'],
    description: 'A shot of espresso poured over milk and ice for a refreshing coffee hit.',
  },
  {
    id: 'drink-20',
    name: 'Iced Chocolate',
    category: 'cat-2',
    basePrice: 4.75,
    baseCost: 1.5,
    imageUrl: 'https://images.unsplash.com/photo-1587882390399-190644f0525d' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-4'],
    description: 'Rich chocolate syrup mixed with cold milk, served over ice.',
  },
  {
    id: 'drink-21',
    name: 'Iced Matcha Latte',
    category: 'cat-2',
    basePrice: 5.00,
    baseCost: 1.6,
    imageUrl: 'https://images.unsplash.com/photo-1509082025158-6c827339734e' + IMG_PARAMS,
    modifierGroups: ['mod-group-1', 'mod-group-2'],
    description: 'Vibrant Japanese green tea powder whisked with cold milk and served over ice.',
  },
  // Other
  {
    id: 'drink-16',
    name: 'Babyccino',
    category: 'cat-4',
    basePrice: 1.5,
    baseCost: 0.5,
    imageUrl: 'https://images.unsplash.com/photo-1610892013197-01e409395f17' + IMG_PARAMS,
    modifierGroups: [],
    description: 'Steamed, frothy milk in a tiny cup, perfect for the little ones.',
  },
  {
    id: 'drink-17',
    name: 'Cookie',
    category: 'cat-4',
    basePrice: 3.0,
    baseCost: 1.0,
    imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35' + IMG_PARAMS,
    modifierGroups: [],
    description: 'A freshly baked, deliciously chewy cookie, the perfect partner for any drink.',
  },
  {
    id: 'drink-18',
    name: 'Coffee Beans',
    category: 'cat-4',
    basePrice: 18.0,
    baseCost: 9.0,
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93' + IMG_PARAMS,
    modifierGroups: [],
    description: 'Take our signature house blend home with you; whole beans for ultimate freshness.',
  },
  {
    id: 'drink-23',
    name: 'Affogato',
    category: 'cat-4',
    basePrice: 5.50,
    baseCost: 2.0,
    imageUrl: 'https://images.unsplash.com/photo-1627762226499-2245d44a29a1' + IMG_PARAMS,
    modifierGroups: [],
    description: 'A scoop of vanilla ice cream drowned with a shot of hot espresso. A perfect dessert.',
  },
];

export const INITIAL_DISCOUNTS: Discount[] = [
    { id: 'disc-1', code: 'STAFF10', type: 'percentage', value: 10 },
    { id: 'disc-2', code: '50OFF', type: 'percentage', value: 50 },
    { id: 'disc-3', code: '2DOLLARSOFF', type: 'fixed', value: 2 },
];

export const COFFEE_JOKES = [
  "What do you call a sad cup of coffee? Depresso.",
  "How did the hipster burn his tongue? He drank his coffee before it was cool.",
  "What’s the best Beatles song? Latte Be!",
  "Why are programmers so bad at making coffee? They can't handle the exceptions.",
  "What's it called when you steal someone's coffee? Mugging!",
  "How does Moses make his coffee? Hebrews it.",
  "What's the opposite of coffee? Sneezy.",
];
